version: '3'

services:
  mindustry-server:
    image: clementz/mindustry-server
    container_name: "mindustry-server"

    volumes:
      #- "/path/to/config:/opt/mindustry/config"

    # set interactive
    tty: true
    stdin_open: true
    
    environment:
      - PUID=1000
      - PGID=1000
      #- MINDUSTRY_ARGS=host,status
      - MINDUSTRY_ARGS=

    ports:
      - "6567:6567"
      - "6567:6567/udp"
